/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.27.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ApiCertificate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-24T10:46:41.519+01:00[Europe/London]")
public class ApiCertificate {
  @SerializedName("expiresOn")
  private Long expiresOn = null;

  @SerializedName("fingerprint")
  private String fingerprint = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("issuedOn")
  private Long issuedOn = null;

  @SerializedName("issuerCommonName")
  private String issuerCommonName = null;

  @SerializedName("issuerOrganization")
  private String issuerOrganization = null;

  @SerializedName("issuerOrganizationalUnit")
  private String issuerOrganizationalUnit = null;

  @SerializedName("pem")
  private String pem = null;

  @SerializedName("serialNumber")
  private String serialNumber = null;

  @SerializedName("subjectCommonName")
  private String subjectCommonName = null;

  @SerializedName("subjectOrganization")
  private String subjectOrganization = null;

  @SerializedName("subjectOrganizationalUnit")
  private String subjectOrganizationalUnit = null;

  public ApiCertificate expiresOn(Long expiresOn) {
    this.expiresOn = expiresOn;
    return this;
  }

   /**
   * Get expiresOn
   * @return expiresOn
  **/
  @Schema(description = "")
  public Long getExpiresOn() {
    return expiresOn;
  }

  public void setExpiresOn(Long expiresOn) {
    this.expiresOn = expiresOn;
  }

  public ApiCertificate fingerprint(String fingerprint) {
    this.fingerprint = fingerprint;
    return this;
  }

   /**
   * Get fingerprint
   * @return fingerprint
  **/
  @Schema(description = "")
  public String getFingerprint() {
    return fingerprint;
  }

  public void setFingerprint(String fingerprint) {
    this.fingerprint = fingerprint;
  }

  public ApiCertificate id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ApiCertificate issuedOn(Long issuedOn) {
    this.issuedOn = issuedOn;
    return this;
  }

   /**
   * Get issuedOn
   * @return issuedOn
  **/
  @Schema(description = "")
  public Long getIssuedOn() {
    return issuedOn;
  }

  public void setIssuedOn(Long issuedOn) {
    this.issuedOn = issuedOn;
  }

  public ApiCertificate issuerCommonName(String issuerCommonName) {
    this.issuerCommonName = issuerCommonName;
    return this;
  }

   /**
   * Get issuerCommonName
   * @return issuerCommonName
  **/
  @Schema(description = "")
  public String getIssuerCommonName() {
    return issuerCommonName;
  }

  public void setIssuerCommonName(String issuerCommonName) {
    this.issuerCommonName = issuerCommonName;
  }

  public ApiCertificate issuerOrganization(String issuerOrganization) {
    this.issuerOrganization = issuerOrganization;
    return this;
  }

   /**
   * Get issuerOrganization
   * @return issuerOrganization
  **/
  @Schema(description = "")
  public String getIssuerOrganization() {
    return issuerOrganization;
  }

  public void setIssuerOrganization(String issuerOrganization) {
    this.issuerOrganization = issuerOrganization;
  }

  public ApiCertificate issuerOrganizationalUnit(String issuerOrganizationalUnit) {
    this.issuerOrganizationalUnit = issuerOrganizationalUnit;
    return this;
  }

   /**
   * Get issuerOrganizationalUnit
   * @return issuerOrganizationalUnit
  **/
  @Schema(description = "")
  public String getIssuerOrganizationalUnit() {
    return issuerOrganizationalUnit;
  }

  public void setIssuerOrganizationalUnit(String issuerOrganizationalUnit) {
    this.issuerOrganizationalUnit = issuerOrganizationalUnit;
  }

  public ApiCertificate pem(String pem) {
    this.pem = pem;
    return this;
  }

   /**
   * Get pem
   * @return pem
  **/
  @Schema(description = "")
  public String getPem() {
    return pem;
  }

  public void setPem(String pem) {
    this.pem = pem;
  }

  public ApiCertificate serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @Schema(description = "")
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public ApiCertificate subjectCommonName(String subjectCommonName) {
    this.subjectCommonName = subjectCommonName;
    return this;
  }

   /**
   * Get subjectCommonName
   * @return subjectCommonName
  **/
  @Schema(description = "")
  public String getSubjectCommonName() {
    return subjectCommonName;
  }

  public void setSubjectCommonName(String subjectCommonName) {
    this.subjectCommonName = subjectCommonName;
  }

  public ApiCertificate subjectOrganization(String subjectOrganization) {
    this.subjectOrganization = subjectOrganization;
    return this;
  }

   /**
   * Get subjectOrganization
   * @return subjectOrganization
  **/
  @Schema(description = "")
  public String getSubjectOrganization() {
    return subjectOrganization;
  }

  public void setSubjectOrganization(String subjectOrganization) {
    this.subjectOrganization = subjectOrganization;
  }

  public ApiCertificate subjectOrganizationalUnit(String subjectOrganizationalUnit) {
    this.subjectOrganizationalUnit = subjectOrganizationalUnit;
    return this;
  }

   /**
   * Get subjectOrganizationalUnit
   * @return subjectOrganizationalUnit
  **/
  @Schema(description = "")
  public String getSubjectOrganizationalUnit() {
    return subjectOrganizationalUnit;
  }

  public void setSubjectOrganizationalUnit(String subjectOrganizationalUnit) {
    this.subjectOrganizationalUnit = subjectOrganizationalUnit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiCertificate apiCertificate = (ApiCertificate) o;
    return Objects.equals(this.expiresOn, apiCertificate.expiresOn) &&
        Objects.equals(this.fingerprint, apiCertificate.fingerprint) &&
        Objects.equals(this.id, apiCertificate.id) &&
        Objects.equals(this.issuedOn, apiCertificate.issuedOn) &&
        Objects.equals(this.issuerCommonName, apiCertificate.issuerCommonName) &&
        Objects.equals(this.issuerOrganization, apiCertificate.issuerOrganization) &&
        Objects.equals(this.issuerOrganizationalUnit, apiCertificate.issuerOrganizationalUnit) &&
        Objects.equals(this.pem, apiCertificate.pem) &&
        Objects.equals(this.serialNumber, apiCertificate.serialNumber) &&
        Objects.equals(this.subjectCommonName, apiCertificate.subjectCommonName) &&
        Objects.equals(this.subjectOrganization, apiCertificate.subjectOrganization) &&
        Objects.equals(this.subjectOrganizationalUnit, apiCertificate.subjectOrganizationalUnit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiresOn, fingerprint, id, issuedOn, issuerCommonName, issuerOrganization, issuerOrganizationalUnit, pem, serialNumber, subjectCommonName, subjectOrganization, subjectOrganizationalUnit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiCertificate {\n");
    
    sb.append("    expiresOn: ").append(toIndentedString(expiresOn)).append("\n");
    sb.append("    fingerprint: ").append(toIndentedString(fingerprint)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    issuedOn: ").append(toIndentedString(issuedOn)).append("\n");
    sb.append("    issuerCommonName: ").append(toIndentedString(issuerCommonName)).append("\n");
    sb.append("    issuerOrganization: ").append(toIndentedString(issuerOrganization)).append("\n");
    sb.append("    issuerOrganizationalUnit: ").append(toIndentedString(issuerOrganizationalUnit)).append("\n");
    sb.append("    pem: ").append(toIndentedString(pem)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    subjectCommonName: ").append(toIndentedString(subjectCommonName)).append("\n");
    sb.append("    subjectOrganization: ").append(toIndentedString(subjectOrganization)).append("\n");
    sb.append("    subjectOrganizationalUnit: ").append(toIndentedString(subjectOrganizationalUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
