/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.27.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BlobStoreApiSoftQuota;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * GroupBlobStoreApiResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-24T10:46:41.519+01:00[Europe/London]")
public class GroupBlobStoreApiResponse {
  @SerializedName("softQuota")
  private BlobStoreApiSoftQuota softQuota = null;

  @SerializedName("members")
  private List<String> members = null;

  /**
   * Gets or Sets fillPolicy
   */
  @JsonAdapter(FillPolicyEnum.Adapter.class)
  public enum FillPolicyEnum {
    ROUNDROBIN("roundRobin"),
    WRITETOFIRST("writeToFirst");

    private String value;

    FillPolicyEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FillPolicyEnum fromValue(String text) {
      for (FillPolicyEnum b : FillPolicyEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FillPolicyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FillPolicyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FillPolicyEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return FillPolicyEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("fillPolicy")
  private FillPolicyEnum fillPolicy = null;

  @SerializedName("name")
  private String name = null;

  public GroupBlobStoreApiResponse softQuota(BlobStoreApiSoftQuota softQuota) {
    this.softQuota = softQuota;
    return this;
  }

   /**
   * Get softQuota
   * @return softQuota
  **/
  @Schema(description = "")
  public BlobStoreApiSoftQuota getSoftQuota() {
    return softQuota;
  }

  public void setSoftQuota(BlobStoreApiSoftQuota softQuota) {
    this.softQuota = softQuota;
  }

  public GroupBlobStoreApiResponse members(List<String> members) {
    this.members = members;
    return this;
  }

  public GroupBlobStoreApiResponse addMembersItem(String membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<String>();
    }
    this.members.add(membersItem);
    return this;
  }

   /**
   * List of the names of blob stores that are members of this group
   * @return members
  **/
  @Schema(description = "List of the names of blob stores that are members of this group")
  public List<String> getMembers() {
    return members;
  }

  public void setMembers(List<String> members) {
    this.members = members;
  }

  public GroupBlobStoreApiResponse fillPolicy(FillPolicyEnum fillPolicy) {
    this.fillPolicy = fillPolicy;
    return this;
  }

   /**
   * Get fillPolicy
   * @return fillPolicy
  **/
  @Schema(description = "")
  public FillPolicyEnum getFillPolicy() {
    return fillPolicy;
  }

  public void setFillPolicy(FillPolicyEnum fillPolicy) {
    this.fillPolicy = fillPolicy;
  }

  public GroupBlobStoreApiResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupBlobStoreApiResponse groupBlobStoreApiResponse = (GroupBlobStoreApiResponse) o;
    return Objects.equals(this.softQuota, groupBlobStoreApiResponse.softQuota) &&
        Objects.equals(this.members, groupBlobStoreApiResponse.members) &&
        Objects.equals(this.fillPolicy, groupBlobStoreApiResponse.fillPolicy) &&
        Objects.equals(this.name, groupBlobStoreApiResponse.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(softQuota, members, fillPolicy, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupBlobStoreApiResponse {\n");
    
    sb.append("    softQuota: ").append(toIndentedString(softQuota)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    fillPolicy: ").append(toIndentedString(fillPolicy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
