/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.27.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.IqConnectionXo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManageIqServerConfigurationApi
 */
@Ignore
public class ManageIqServerConfigurationApiTest {

    private final ManageIqServerConfigurationApi api = new ManageIqServerConfigurationApi();

    /**
     * Disable IQ server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void disableIqTest() throws ApiException {
        api.disableIq();

        // TODO: test validations
    }
    /**
     * Enable IQ server
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enableIqTest() throws ApiException {
        api.enableIq();

        // TODO: test validations
    }
    /**
     * Get IQ server configuration
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConfigurationTest() throws ApiException {
        api.getConfiguration();

        // TODO: test validations
    }
    /**
     * Update IQ server configuration
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateConfigurationTest() throws ApiException {
        IqConnectionXo body = null;
        api.updateConfiguration(body);

        // TODO: test validations
    }
    /**
     * Verify IQ server connection
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyConnectionTest() throws ApiException {
        api.verifyConnection();

        // TODO: test validations
    }
}
