/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.27.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.RoutingRuleXO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RoutingRulesApi
 */
@Ignore
public class RoutingRulesApiTest {

    private final RoutingRulesApi api = new RoutingRulesApi();

    /**
     * Create a single routing rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRoutingRuleTest() throws ApiException {
        RoutingRuleXO body = null;
        api.createRoutingRule(body);

        // TODO: test validations
    }
    /**
     * Delete a single routing rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRoutingRuleTest() throws ApiException {
        String name = null;
        api.deleteRoutingRule(name);

        // TODO: test validations
    }
    /**
     * Get a single routing rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRoutingRuleTest() throws ApiException {
        String name = null;
        RoutingRuleXO response = api.getRoutingRule(name);

        // TODO: test validations
    }
    /**
     * List routing rules
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRoutingRulesTest() throws ApiException {
        List<RoutingRuleXO> response = api.getRoutingRules();

        // TODO: test validations
    }
    /**
     * Update a single routing rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRoutingRuleTest() throws ApiException {
        RoutingRuleXO body = null;
        String name = null;
        api.updateRoutingRule(body, name);

        // TODO: test validations
    }
}
